### ISSUE TITLE
v1.13 is missing updated files

### ISSUE THREAD

**Issue by tristanluther28** [omrips/viewstl#17]
parser.js in src and parser.min.js in build are not updated with the functions `parse_3mf()` and `parse_3mf_from_txt()` as well as the updated switch statement that allow 3mf files to be interpreted. 

The updated files are present on the website https://www.viewstl.com/.

Additionally, jszip should be included in the build or marked as a dependency for the new update.

Thanks,
Tristan

**Comment by tristanluther28** [comment]
Additionally with the updated code, the 3mf file 3dmodel.model cannot be read if the `<build>` tag includes the p:UUID. See this example production file https://github.com/3MFConsortium/spec_production/blob/master/3MF%20Production%20Extension.md#appendix-c-3mf-samples
 The returned object cannot render and has dimensions of -Infinity in all directions.

**Comment by omrips** [comment]
Thanks Tristan!! parser.js indeed was missing. but parser.min.js was ok me think. fixed now.
(updated and reuploaded this file anyway (because of the p:UUUID tag fix) )

Please let me know if now works as expected.

(I do not think jszip.js should be included here, as it is only required with 3mf and vsb files, what I need to do is to create a  npm helper for this plugin. which will handle all of the dependencies ... )

**Comment by tristanluther28** [comment]
Thanks for getting on this so quick

Everything is running smoothly now 🥇 

The npm installer would be convenient. I think for now, a link and note in the README.md about jszip would help.
